#!/usr/bin/env node

var idk = require( 'imazzine-developer-kit' );
var args = process.argv.slice(2);

if( args[ 0 ] === '-a' || args[ 0 ] === '--application' ){

    idk.compiler.compileApplication( );
}
if( args[ 0 ] === '-t' || args[ 0 ] === '--templates' ){

    idk.template.compileTemplates( );
}