#!/usr/bin/env node

var idk = require( 'imazzine-developer-kit' );
var args = process.argv.slice(2);
if( args[ 0 ] === 'compile' ){

    if( !args[ 1 ] ){

        getHelp( );
    }
    if( args[ 1 ] === 'app' ){

        idk.compiler.compileApplication( );

    }else if( args[ 1 ] === 'soy' ){

        idk.template.compileTemplates( );

    }else if( args[ 1 ] === 'scss' ){

        idk.stylesheet.scss2gss( );

    }else if( args[ 1 ] === 'gss' ){

        idk.stylesheet.gss2css( );

    }else{

        getHelp( );
    }
}else if( args[ 0 ] === 'calcdeps' ){

    idk.compiler.calculateDependencies( );

}else if( args[ 0 ] === 'extractmsg' ){

    idk.template.extractMessages( );

}else if( args[ 0 ] === 'help' ){

    getHelp( );

}else{

    getHelp( );
}
function getHelp( ){

    console.log( '' );
    console.log( 'Usage: idk <command>' );
    console.log( '' );
    console.log( 'where <command> is one of:' );
    console.log( '    help                see this help' );
    console.log( '    compile <argument>  running compiling process of specified in argument entity: app, soy, scss, gss' );
    console.log( '    calcdeps            running dependency calculation process' );
    console.log( '    extractmsg          extract i18n messages from soy files' );
    console.log( '' );
}