#!/usr/bin/env node

var idk = require( 'imazzine-developer-kit' );
var args = process.argv.slice(2);

if( args[ 0 ] === '--compile' ){

    if( !args[ 1 ] ){

        console.log( 'Error! Second argument must be specified. Use --help argument to see help.' );
    }
    if( args[ 1 ] === '--app' ){

        idk.compiler.compileApplication( );
    }
    if( args[ 1 ] === '--tpl' ){

        idk.template.compileTemplates( );
    }
    if( args[ 1 ] === '--scss' ){

        idk.stylesheet.scss2gss( );
    }
    if( args[ 1 ] === '--gss' ){

        idk.stylesheet.gss2css( );
    }
}
if( args[ 0 ] === '--calcdeps' ){

    idk.compiler.calculateDependencies( );
}
if( args[ 0 ] === '--extractmsg' ){

    idk.template.extractMessages( );
}