#!/usr/bin/env node

var idk = require( 'imazzine-developer-kit' );
var args = process.argv.slice(2);
if( args[ 0 ] === 'compile' ){

    if( !args[ 1 ] ){

        getHelp( );
    }
    if( args[ 1 ] === 'app' ){

        idk.compiler.compileApplication( );

    }else if( args[ 1 ] === 'js' ){

        idk.compiler.compileJs( );

    }else if( args[ 1 ] === 'soy' ){

        idk.template.compileTemplates( );

    }else if( args[ 1 ] === 'scss' ){

        idk.stylesheet.scss2gss( );

    }else if( args[ 1 ] === 'gss' ){

        idk.stylesheet.gss2css( );

    }else if( args[ 1 ] === 'css' ){

         idk.stylesheet.css( );

    }else{

        getHelp( );
    }
}else if( args[ 0 ] === 'calcdeps' ){

    idk.compiler.calculateDependencies( );

}else if( args[ 0 ] === 'extractmsg' ){

     idk.template.extractMessages( );

 }else if( args[ 0 ] === 'start' ){

    if( !args[ 1 ] ){

        getHelp( );
    }
    if( args[ 1 ] === 'server' ){

        idk.server.startServer( );
    }

}else if( args[ 0 ] === 'update' ){

    idk.filetools.execute( 'git pull' );
    idk.filetools.execute( 'npm update' );

}else if( args[ 0 ] === 'publish' ){

    idk.compiler.calculateDependencies( );
    idk.compiler.compileApplication( );
    idk.filetools.execute( 'git add .' );
    idk.filetools.execute( 'git commit -a -m "idk auto commit [' + ( new Date( ) ).toISOString( ) + ']"' );
    idk.filetools.execute( 'git pull' );
    idk.filetools.execute( 'git push' );
    idk.filetools.execute( 'npm publish' );

}else if( args[ 0 ] === 'help' ){

    getHelp( );

}else{

    getHelp( );
}
function getHelp( ){

    console.log( '' );
    console.log( 'Usage: idk <command>' );
    console.log( '' );
    console.log( 'where <command> is one of:' );
    console.log( '    help                see this help' );
    console.log( '    compile <argument>  running compiling process of specified in argument entity: app, js, soy, css, scss, gss' );
    console.log( '    calcdeps            running dependency calculation process' );
    console.log( '    extractmsg          extract i18n messages from soy files' );
    console.log( '    update              update module from repositories' );
    console.log( '    publish             publish module' );
    console.log( '' );
}